// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

/* This file contains certs needed to communicate with Azure (IoT) */

#include "cert.h"

//const unsigned char caCertBuf[] =
///* DigiCert Baltimore Root */
//"-----BEGIN CERTIFICATE-----\r\n"
//"MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ\r\n"
//"RTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD\r\n"
//"VQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoX\r\n"
//"DTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9y\r\n"
//"ZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFsdGltb3JlIEN5YmVy\r\n"
//"VHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMEuyKr\r\n"
//"mD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjr\r\n"
//"IZ3AQSsBUnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeK\r\n"
//"mpYcqWe4PwzV9/lSEy/CG9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSu\r\n"
//"XmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9XbIGevOF6uvUA65ehD5f/xXtabz5OTZy\r\n"
//"dc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjprl3RjM71oGDHweI12v/ye\r\n"
//"jl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoIVDaGezq1\r\n"
//"BE3wMBIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3\r\n"
//"DQEBBQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT92\r\n"
//"9hkTI7gQCvlYpNRhcL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3Wgx\r\n"
//"jkzSswF07r51XgdIGn9w/xZchMB5hbgF/X++ZRGjD8ACtPhSNzkE1akxehi/oCr0\r\n"
//"Epn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsaY71k5h+3zvDyny67G7fyUIhz\r\n"
//"ksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9HRCwBXbsdtTLS\r\n"
//"R9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp\r\n"
//"-----END CERTIFICATE-----\r\n"
//;
// MyTestServer
const unsigned char caCertBuf[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIDpzCCAo+gAwIBAgIJAMGVRewzNkTFMA0GCSqGSIb3DQEBDQUAMGoxFzAVBgNV\r\n"
"BAMMDkFuIE1RVFQgYnJva2VyMRYwFAYDVQQKDA1Pd25UcmFja3Mub3JnMRQwEgYD\r\n"
"VQQLDAtnZW5lcmF0ZS1DQTEhMB8GCSqGSIb3DQEJARYSbm9ib2R5QGV4YW1wbGUu\r\n"
"bmV0MB4XDTE4MTEyMzA4MjgwMVoXDTMyMTExOTA4MjgwMVowajEXMBUGA1UEAwwO\r\n"
"QW4gTVFUVCBicm9rZXIxFjAUBgNVBAoMDU93blRyYWNrcy5vcmcxFDASBgNVBAsM\r\n"
"C2dlbmVyYXRlLUNBMSEwHwYJKoZIhvcNAQkBFhJub2JvZHlAZXhhbXBsZS5uZXQw\r\n"
"ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDxHHEWEIuz949x6kCno2Au\r\n"
"gETazyAb3AlB7leuukrmrAUuj0AQCyutJ5QquAohIZ3EZaiSV5HxFggIZl8z2uZ7\r\n"
"WzeeuRpxG5Imi8EAHtu850ybOyWz0yL9OXHs6lwoBtnEjLvX7C6040u2ADyNuwRn\r\n"
"pAICRneiEHZunrGTE2q4oLwqeP1y4on9SGmoR4NlclF0WhDse5IOADcpQT88BTZc\r\n"
"d2ZBSIZYK5+LjGJgOjL5mB74j+qtktQD4SxAxNndP7iKdTkEXYuVWiK2MT8pgvX8\r\n"
"U8AmtN9ocWdjvL0iTBIwBW3VBv+QQDkvrKZb0CwZ/EIf1imlN2lHYHyULnBq6NX/\r\n"
"AgMBAAGjUDBOMB0GA1UdDgQWBBT9OzQrhPqRcb/egvw4A+0/yLG9vjAfBgNVHSME\r\n"
"GDAWgBT9OzQrhPqRcb/egvw4A+0/yLG9vjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3\r\n"
"DQEBDQUAA4IBAQAEt2mdFKcC4vOvpcfOhTM6LK4WgmBQmMqY8LIDVzjuqvQUbulb\r\n"
"NaT7/DckSWGuUas8DDPviTu8IVmPN3Cjkal52s6n8cORTHJeRKrW+PMGtNxUjyqf\r\n"
"26QI67bL3dmvO1GQWsvNLQArjdivPFBThXa4DRQviIT2s9KK37NXOz0b/dCG1yOj\r\n"
"2x3QU8Jo1daRztJPQKBG+1ba3nVG2nwcb+MRrWmCnPEj1iw92EkP68Qd/hckYIhO\r\n"
"3YQ1V2GGmx+M2JaPg5xLk0KOsxcPtw1MxPObLZ14bJ8CQ7m+NOvMPBAeK8cdcHyT\r\n"
"+FTCboaVd+7zgfo5fq9b1jNpOVsAmjhVaKWt\r\n"
"-----END CERTIFICATE-----\r\n"
;